desktop mode

diff --git a/pardus-boot-repair b/pardus-boot-repair
--- a/pardus-boot-repair
+++ b/pardus-boot-repair
@@ -70,6 +70,7 @@ while true ; do
         "grub"       "$(eval_gettext "Reinstall grub")" \
         "password"   "$(eval_gettext "Reset password")" \
         "chroot"     "$(eval_gettext "Open chroot shell")" \
+        "desktop"    "$(eval_gettext "Open desktop")" \
         "reinstall"  "$(eval_gettext "Reinstall system")" \
         "update"     "$(eval_gettext "Update system")" \
     )
@@ -112,6 +113,14 @@ while true ; do
         user=$(select_user)
         if [[ "$user" != "" ]] ; then
             x-terminal-emulator -e "pardus-chroot /dev/$disk su $user -" || fail $(eval_gettext "Failed to open chroot shell")
+        fi
+    elif [[ "$selection" == "desktop" ]] ; then
+        xhost +
+        user=$(select_user)
+        if [[ "$user" != "" ]] ; then
+            Xephyr :1 -title $(eval_gettext "Virtual desktop") &
+            env DISPLAY=:1 pardus-chroot /dev/$disk su $user -c '/etc/X11/xinit/xinitrc' || fail $(eval_gettext "Failed to open desktop")
+            pkill Xephyr
         fi
     elif [[ "$selection" == "reinstall" ]] ; then
         yesno "$(eval_gettext "This operation may damage your files! Do you want to continue?")"
