implovement

diff --git a/pardus-boot-repair b/pardus-boot-repair
--- a/pardus-boot-repair
+++ b/pardus-boot-repair
@@ -33,6 +33,11 @@ select_user(){
     umount /mnt
 }
 
+fail(){
+    zenity --error --text="$@" --ok-label="$(eval_gettext "OK")"
+    return 1
+}
+
 disk=$(zenity --list \
         --title="$(eval_gettext "Select rootfs partition")" \
         --cancel-label="$(eval_gettext "Exit")" \
@@ -54,6 +59,7 @@ while true ; do
         "grub"       "$(eval_gettext "Reinstall grub")" \
         "password"   "$(eval_gettext "Reset password")" \
         "chroot"     "$(eval_gettext "Open chroot shell")" \
+        "reinstall"  "$(eval_gettext "Reinstall system")" \
     )
     if [[ "$selection" == "grub" ]] ; then
         mbr=$(zenity --list \
@@ -79,18 +85,20 @@ while true ; do
                 exit
             fi
         fi
-        x-terminal-emulator -e "env disk=$disk mbr=$mbr efi=$efi grub-reinstall"
+        x-terminal-emulator -e "env disk=$disk mbr=$mbr efi=$efi grub-reinstall" || fail $(eval_gettext "Failed to reinstall grub")
     elif [[ "$selection" == "password" ]] ; then
         user=$(select_user)
         if [[ "$user" != "" ]] ; then
-            x-terminal-emulator -e "env user=$user disk=$disk reset-password"
+            x-terminal-emulator -e "env user=$user disk=$disk reset-password" || fail $(eval_gettext "Failed to reset password")
         fi
     elif [[ "$selection" == "chroot" ]] ; then
         xhost +
         user=$(select_user)
         if [[ "$user" != "" ]] ; then
-            x-terminal-emulator -e "pardus-chroot /dev/$disk su $user -"
+            x-terminal-emulator -e "pardus-chroot /dev/$disk su $user -" || fail $(eval_gettext "Failed to open chroot shell")
         fi
+    elif [[ "$selection" == "reinstall" ]] ; then
+        x-terminal-emulator -e "pardus-reinstall /dev/$disk"
     else
         exit 0
     fi
