boot repair check filesystem

diff --git a/pardus-boot-repair b/pardus-boot-repair
--- a/pardus-boot-repair
+++ b/pardus-boot-repair
@@ -55,6 +55,7 @@ disk=$(zenity --list \
 if [[ "$disk" == "" ]] ; then
     exit 0
 fi
+x-terminal-emulator -e "check-filesystem"
 mount -o ro /dev/$disk /mnt
 if [[ ! -f /mnt/etc/os-release ]] ; then
     fail "Invalid rootfs partition: /dev/$disk"
@@ -72,6 +73,7 @@ while true ; do
         "chroot"     "$(eval_gettext "Open chroot shell")" \
         "reinstall"  "$(eval_gettext "Reinstall system")" \
         "update"     "$(eval_gettext "Update system")" \
+        "fix-broken" "$(eval_gettext "Try to fix broken packages")" \
     )
     if [[ "$selection" == "grub" ]] ; then
         mbr=$(zenity --list \
@@ -113,6 +115,8 @@ while true ; do
         if [[ "$user" != "" ]] ; then
             x-terminal-emulator -e "pardus-chroot /dev/$disk su $user -" || fail $(eval_gettext "Failed to open chroot shell")
         fi
+    elif [[ "$selection" == "fix-broken" ]] ; then
+        x-terminal-emulator -e "env disk=$disk fix-broken-packages" || fail $(eval_gettext "Failed to fix broken packages")
     elif [[ "$selection" == "reinstall" ]] ; then
         yesno "$(eval_gettext "This operation may damage your files! Do you want to continue?")"
         mbr=$(zenity --list \
