feat: initial LVM support

diff --git a/src/scripts/pardus-mount-rootfs b/src/scripts/pardus-mount-rootfs
--- a/src/scripts/pardus-mount-rootfs
+++ b/src/scripts/pardus-mount-rootfs
@@ -32,6 +32,55 @@ if [[ $fs == 'crypto_LUKS' ]] ||  [[ $fs == 'crypto' ]]; then
     fs="$(lsblk -no FSTYPE /dev/$disk | tr -d '\n' | head -n 1)"
 fi
 
+if [[ $fs == 'LVM2_member' ]]; then
+    # detect volume groups
+    VG_NAMES=($(vgdisplay --colon | awk -F: '{print $1}' | xargs))
+    if [ ${#VG_NAMES[@]} -eq 0 ]; then
+      echo "No volume groups found."
+      exit 1
+    elif [ ${#VG_NAMES[@]} -gt 1 ]; then
+      while true; do
+        echo "Multiple volume groups found, please select one of:"
+        echo ${VG_NAMES[@]}
+        read -p "volume group >>> " VG_NAME
+        if [[ ${VG_NAMES[@]} =~ $VG_NAME ]]; then
+          break
+        else
+          echo "Invalid input. Please enter a valid number."
+        fi
+      done
+    else
+      VG_NAME=${VG_NAMES[0]}
+    fi
+    vgchange -ay $VG_NAME
+
+    # Find the logical volumes
+    LV_NAMES=($(lvdisplay --colon | grep ":$VG_NAME:" | awk -F: '{print $1}'))
+    for lv in ${!LV_NAMES[@]}; do
+        LV_NAMES[$lv]=$(echo ${LV_NAMES[$lv]} | sed "s/.*\/$VG_NAME\///")
+    done
+    if [ ${#LV_NAMES[@]} -eq 0 ]; then
+      echo "No logical volumes found."
+      exit 1
+    elif [ ${#LV_NAMES[@]} -gt 1 ]; then
+      while true; do
+        echo "Multiple logical volumes found, please select one of:"
+        echo "${!LV_NAMES[@]}"
+        read -p "logical volume >>> " LV_NAME
+        if [[ ${!LV_NAMES[@]} =~ $LV_NAME ]]; then
+          break
+        else
+          echo "Invalid input. Please enter a valid number."
+        fi
+      done
+    else
+      LV_NAME=${LV_NAMES[0]}
+    fi
+    # LV_NAME=$(echo $LV_NAME | sed "s/.*\/$VG_NAME\///")
+    disk="$VG_NAME/$LV_NAME"
+    fs="$(lsblk -no FSTYPE /dev/$disk | tr -d '\n')"
+fi
+
 mount /dev/$disk "$DESTDIR"
 
 # btrfs subvolumes
